# arxivの学問領域の指定
subject: 'cat:q-bio.*'

# 検索キーワード
keywords:
        microbiome: 1
        air microbiome: 1
        machine: 1
        Qiime2: 1
        new generation sequencing: 1
        chemosignal: 1

# 通知の閾値
score_threshold: 0
